' ----------------------------------------------
' Script generated by SIwave 2022 R2
' Sun Nov 26 14:07:17 2023
' ----------------------------------------------
Dim oAnsoftApp
Dim oDesktop
Dim oProject
Dim oDesign
Dim oEditor
Dim oModule
Dim oCompId
Dim oCompId1
Dim oCompId2
Redim oCompIdIbisArr(100)
Dim oBkupCurrDesign
Dim autoSave
Dim x
Dim y
Dim angle
Dim flip
Dim compPins
Dim compPinInfo
Dim portCnt
Dim pin
Dim pagePortId
Dim dx
Dim str
Dim strArr
Dim locale
locale = GetLocale()
SetLocale(1033)
Set oAnsoftApp = CreateObject("Ansoft.ElectronicsDesktop.2022.2")
Set oDesktop = oAnsoftApp.GetAppDesktop()
oDesktop.RestoreWindow
autoSave = oDesktop.GetAutoSaveEnabled()
oDesktop.EnableAutoSave(False)
Set oProject = oDesktop.NewProject()
oProject.InsertDesign "Circuit Design", "openrex_edb_v3_TDR1", "", ""
Set oDesign = oProject.SetActiveDesign("openrex_edb_v3_TDR1")
Set oEditor = oDesign.SetActiveEditor("SchematicEditor")
oEditor.SetSIWizardMode(true)
Set oDesign = oProject.SetActiveDesign("openrex_edb_v3_TDR1")
oProject.SaveAs "C:/Users/SGI-U3/Documents/GitHub/Ansys/siwave/_03_openrex_u14_disjoint/openrex_edb_v3.siwaveresults/DesignerTDR/TDR1_schematic.aedt", true
Set oDefinitionManager = oProject.GetDefinitionManager()
Set oModelManager = oDefinitionManager.GetManager("Model")
oModelManager.Add Array("NAME:openrex_edb_v3", "Name:=", "openrex_edb_v3", "ModTime:=", 1700995037, _
"Library:=", "", "LibLocation:=", "Project", "ModelType:=", "siwave", "Description:=", "", _
"filename:=", "$PROJECTDIR/../../openrex_edb_v3.siw", "numberofports:=", 20, "DesignName:=", "openrex_edb_v3", _
"SolutionName:=", "TDRwizard Sim", "Simulate:=", true, "CloseProject:=",  false, "SaveProject:=", true, _
"InterpY:=", true, "InterpAlg:=", "auto", "NewToOldMap:=", Array(), "OldToNewMap:=", Array(), "PinNames:=", Array( _
"DRAM_D0_AD2_PBGA624_U1", _
"DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D1_AE2_PBGA624_U1", _
"DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D2_AC4_PBGA624_U1", _
"DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D3_AA5_PBGA624_U1", _
"DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D4_AC1_PBGA624_U1", _
"DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D5_AD1_PBGA624_U1", _
"DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D6_AB4_PBGA624_U1", _
"DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_D7_AE4_PBGA624_U1", _
"DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_DQS0_N_AD3_PBGA624_U1", _
"DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", _
"DRAM_DQS0_P_AE3_PBGA624_U1", _
"DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2"), _
"IgnoreDepVars:=", false, Array("NAME:DesignerCustomization", "DCOption:=",  _
0, "InterpOption:=", 0, "ExtrapOption:=", 1, "Convolution:=", 0, "Passivity:=", false, _
"Reciprocal:=", false, "DataType:=", 1), Array("NAME:NexximCustomization", "DCOption:=",  _
3, "InterpOption:=", 1, "ExtrapOption:=", 3, "Convolution:=", 0, "Passivity:=", false, "Reciprocal:=", false, "DataType:=", 2))
Set oComponentManager = oDefinitionManager.GetManager("Component")
oComponentManager.Add Array("NAME:openrex_edb_v3", "Info:=", Array("Type:=", 13, "NumTerminals:=",  _
20, "DataSource:=", "", "ModifiedOn:=", 1700995037, "Manufacturer:=", "", "Symbol:=",  _
"", "Footprint:=", "", "Description:=", "", "InfoTopic:=", "", "InfoHelpFile:=",  _
"", "IconFile:=", "", "Library:=", "", "OriginalLocation:=", "Project", "IEEE:=",  _
"", "Author:=", "", "OriginalAuthor:=", "", "CreationDate:=", 1700995037, "ExampleFile:=", ""), _
"Refbase:=", "U", "NumParts:=", 1, Array("NAME:Parameters", "TextProp:=", Array("ModelName", "RD", "",  _
"FieldSolver"), "MenuProp:=", Array("CoSimulator", "SD", "", "Default", 0), "ButtonProp:=", Array( _
"CosimDefinition", "SD", "", "Edit", "Edit", 40501, "ButtonPropClientData:=", Array())), Array("NAME:Properties", "TextProp:=", Array( _
"Owner", "RD", "", "SIWave")), "CompExtID:=", 5, Array("NAME:CosimDefinitions", Array("NAME:CosimDefinition", "CosimulatorType:=",  _
105, "CosimDefName:=", "Default", "IsDefinition:=", true, "Connect:=", true, "ModelDefinitionName:=",  _
"openrex_edb_v3", "ShowRefPin:=", false), "DefaultCosim:=", "Default"))
Set oEditor = oDesign.SetActiveEditor("SchematicEditor")
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "openrex_edb_v3", "Id:=", "100"), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.0, "Y:=", 0.0, "Angle:=", 0, "Flip:=", false))
Set oSymbolManager = oDefinitionManager.GetManager("Symbol")
oSymbolManager.EditSymbolAndUpdateComps "openrex_edb_v3", Array("NAME:openrex_edb_v3", "ModTime:=", 1700995037319, "Library:=", "", "ModSinceLib:=", false, _
"LibLocation:=", "Project", "HighestLevel:=", 1, "Normalize:=", false, "InitialLevels:=", Array(0, 1) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D0_AD2_PBGA624_U1", -0.01524, 0.01016, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D0_AD2_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D0_AD2_PBGA624_U1_ref", -0.01016, 0.01016, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D0_AD2_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", -0.01524, 0.00762, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", -0.01016, 0.00762, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D1_AE2_PBGA624_U1", -0.01524, 0.00508, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D1_AE2_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D1_AE2_PBGA624_U1_ref", -0.01016, 0.00508, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D1_AE2_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", -0.01524, 0.00254, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", -0.01016, 0.00254, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D2_AC4_PBGA624_U1", -0.01524, 0, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D2_AC4_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D2_AC4_PBGA624_U1_ref", -0.01016, 0, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D2_AC4_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", -0.01524, -0.00254, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", -0.01016, -0.00254, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D3_AA5_PBGA624_U1", -0.01524, -0.00508, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D3_AA5_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D3_AA5_PBGA624_U1_ref", -0.01016, -0.00508, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D3_AA5_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", -0.01524, -0.00762, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", -0.01016, -0.00762, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D4_AC1_PBGA624_U1", -0.01524, -0.01016, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D4_AC1_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D4_AC1_PBGA624_U1_ref", -0.01016, -0.01016, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D4_AC1_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", -0.01524, -0.0127, 0.00000000000000, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", -0.01016, -0.0127, 0.00000000000000, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D5_AD1_PBGA624_U1", 0.01524, 0.01016, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D5_AD1_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D5_AD1_PBGA624_U1_ref", 0.01016, 0.01016, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D5_AD1_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", 0.01524, 0.00762, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", 0.01016, 0.00762, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D6_AB4_PBGA624_U1", 0.01524, 0.00508, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D6_AB4_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D6_AB4_PBGA624_U1_ref", 0.01016, 0.00508, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D6_AB4_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", 0.01524, 0.00254, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", 0.01016, 0.00254, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D7_AE4_PBGA624_U1", 0.01524, 0, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D7_AE4_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D7_AE4_PBGA624_U1_ref", 0.01016, 0, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D7_AE4_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", 0.01524, -0.00254, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", 0.01016, -0.00254, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_N_AD3_PBGA624_U1", 0.01524, -0.00508, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_DQS0_N_AD3_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_N_AD3_PBGA624_U1_ref", 0.01016, -0.00508, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_DQS0_N_AD3_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", 0.01524, -0.00762, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", 0.01016, -0.00762, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_P_AE3_PBGA624_U1", 0.01524, -0.01016, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_DQS0_P_AE3_PBGA624_U1", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_P_AE3_PBGA624_U1_ref", 0.01016, -0.01016, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_DQS0_P_AE3_PBGA624_U1_ref", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", 0.01524, -0.0127, 3.14159265358979, "N", 0, 0.00254, false, 0, true, "", false, false, "DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", true)) _
,Array("NAME:PinDef", "Pin:=", Array("DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", 0.01016, -0.0127, 3.14159265358979, "N", 0, 0.00254, false, 0, false, "0", false, false, "DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", true)) _
,Array("NAME:Graphics", "Rect:=", Array(0, 0, 0, 0, 0, -0.00127, 0.0254, 0.02794, 0, 0, 0), _
"Rect:=", Array(0, 1, 0, 0, -0.0122767, 0.01016, 0.000423333, 0.000423333, 0, 0, 0)) _
), Array(), Array("NAME:EditContext", "RefPinOption:=", 3, "CompName:=", "openrex_edb_v3", Array("NAME:Terminals" _
,"TermAttributes:=", Array("DRAM_D0_AD2_PBGA624_U1", "DRAM_D0_AD2_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D0_AD2_PBGA624_U1_ref", "DRAM_D0_AD2_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D1_AE2_PBGA624_U1", "DRAM_D1_AE2_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D1_AE2_PBGA624_U1_ref", "DRAM_D1_AE2_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D2_AC4_PBGA624_U1", "DRAM_D2_AC4_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D2_AC4_PBGA624_U1_ref", "DRAM_D2_AC4_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D3_AA5_PBGA624_U1", "DRAM_D3_AA5_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D3_AA5_PBGA624_U1_ref", "DRAM_D3_AA5_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D4_AC1_PBGA624_U1", "DRAM_D4_AC1_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D4_AC1_PBGA624_U1_ref", "DRAM_D4_AC1_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D5_AD1_PBGA624_U1", "DRAM_D5_AD1_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D5_AD1_PBGA624_U1_ref", "DRAM_D5_AD1_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D6_AB4_PBGA624_U1", "DRAM_D6_AB4_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D6_AB4_PBGA624_U1_ref", "DRAM_D6_AB4_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_D7_AE4_PBGA624_U1", "DRAM_D7_AE4_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_D7_AE4_PBGA624_U1_ref", "DRAM_D7_AE4_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_DQS0_N_AD3_PBGA624_U1", "DRAM_DQS0_N_AD3_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_DQS0_N_AD3_PBGA624_U1_ref", "DRAM_DQS0_N_AD3_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
,"TermAttributes:=", Array("DRAM_DQS0_P_AE3_PBGA624_U1", "DRAM_DQS0_P_AE3_PBGA624_U1") _
,"TermAttributes:=", Array("DRAM_DQS0_P_AE3_PBGA624_U1_ref", "DRAM_DQS0_P_AE3_PBGA624_U1_ref") _
,"TermAttributes:=", Array("DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2") _
,"TermAttributes:=", Array("DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref", "DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2_ref") _
))
compPins = oEditor.GetComponentPins(oCompId)
pagePortId = 1100
portCnt = 0
for each pin in compPins
  if portCnt < 40 then
    compPinInfo = oEditor.GetComponentPinInfo(oCompId,pin)
    if UBound(compPinInfo) >= 0 then
      x = CDbl(Mid(compPinInfo(0),InStr(compPinInfo(0),"=") + 1 ))
      y = CDbl(Mid(compPinInfo(1),InStr(compPinInfo(1),"=") + 1 ))
      angle = CDbl(Mid(compPinInfo(2),InStr(compPinInfo(2),"=") + 1 ))
      flip = CBool(Mid(compPinInfo(3),InStr(compPinInfo(3),"=") + 1 ))
      pagePortName = pin
      oCompId1 = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", pagePortName, "Id:=", pagePortId), _
        Array("NAME:Attributes", "Page:=", 1, "X:=", x, "Y:=", y, "Degrees:=", angle, "Flip:=", flip))
      if angle = 180 then
        dx = 0.01016
      else
        dx = -0.01016
      end if
      oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
        oCompId1)), Array("NAME:MoveParameters", "xdelta:=", dx, "ydelta:=", 0.0, _
        "Disconnect:=", false, "Rubberband:=", false)
      pagePortId = pagePortId + 10
    end if
  end if
  portCnt = portCnt + 1
next

oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D0_AD2_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07874, "Y:=", 0.08128, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D0_AD2_PBGA624_U1", "Id:=", 1510), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07366, "Y:=", 0.08128, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D1_AE2_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07874, "Y:=", 0.04064, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D1_AE2_PBGA624_U1", "Id:=", 1530), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07366, "Y:=", 0.04064, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D2_AC4_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07874, "Y:=", 0, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D2_AC4_PBGA624_U1", "Id:=", 1550), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07366, "Y:=", 0, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D3_AA5_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07874, "Y:=", -0.04064, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D3_AA5_PBGA624_U1", "Id:=", 1570), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07366, "Y:=", -0.04064, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D4_AC1_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07874, "Y:=", -0.08128, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D4_AC1_PBGA624_U1", "Id:=", 1590), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.07366, "Y:=", -0.08128, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D5_AD1_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", 0.08128, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D5_AD1_PBGA624_U1", "Id:=", 1610), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.14986, "Y:=", 0.08128, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D6_AB4_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", 0.04064, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D6_AB4_PBGA624_U1", "Id:=", 1630), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.14986, "Y:=", 0.04064, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Single_Ended", "Id:=", "DRAM_D7_AE4_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", 0, "Angle:=", 90, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "50ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D7_AE4_PBGA624_U1", "Id:=", 1650), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.14986, "Y:=", 0, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Probes:TDR_Differential_Ended", "Id:=", "DRAM_DQS0_P_AE3_PBGA624_U1"),  _
Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", -0.04064, "Angle:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", 0.00508, "Disconnect:=", false, "Rubberband:=", false)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers", oCompId), Array("NAME:ChangedProps",  _
Array("NAME:Rise_time", "OverridingDef:=",true, "Value:=", "35ps", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_width", "OverridingDef:=",true, "Value:=", "10us", "NetlistUnits:=", "s"),  _
Array("NAME:Pulse_repetition", "OverridingDef:=",true, "Value:=", "20us", "NetlistUnits:=", "s"),  _
Array("NAME:Z0", "OverridingDef:=", true, "Value:=", "100ohms", "NetlistUnits:=", "ohm"),  _
Array("NAME:Time_delay", "OverridingDef:=",true, "Value:=", "0.5ns", "NetlistUnits:=", "s"))))
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_DQS0_P_AE3_PBGA624_U1", "Id:=", 1670), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", -0.03556, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_DQS0_N_AD3_PBGA624_U1", "Id:=", 1680), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", -0.15494, "Y:=", -0.04572, "Degrees:=", 180, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", 0.0127, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "1", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.08128, "Y:=", 0.08128, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1700), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.08636, "Y:=", 0.07874, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1710), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.0762, "Y:=", 0.08128, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "2", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.08128, "Y:=", 0.04064, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1730), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.08636, "Y:=", 0.0381, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1740), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.0762, "Y:=", 0.04064, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "3", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.08128, "Y:=", 0, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1760), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.08636, "Y:=", -0.00254, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1770), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.0762, "Y:=", 0, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "4", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.08128, "Y:=", -0.04064, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1790), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.08636, "Y:=", -0.04318, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1800), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.0762, "Y:=", -0.04064, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "5", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.08128, "Y:=", -0.08128, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1820), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.08636, "Y:=", -0.08382, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1830), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.0762, "Y:=", -0.08128, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "6", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.15748, "Y:=", 0.08128, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1850), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.16256, "Y:=", 0.07874, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1860), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", 0.08128, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "7", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.15748, "Y:=", 0.04064, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1880), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.16256, "Y:=", 0.0381, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1890), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", 0.04064, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "8", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.15748, "Y:=", 0, "Degrees:=", 0, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "50ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 0, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oEditor.CreateGround Array("NAME:GroundProps", "Id:=", 1910), Array("NAME:Attributes", "Page:=", 1, _
  "X:=", 0.16256, "Y:=", -0.00254, "Angle:=", 0.000000, "Flip:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1920), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", 0, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.03556, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreateComponent ( Array("NAME:ComponentProps", "Name:=", "Nexxim Circuit Elements\Resistors:RES_", "Id:=", "9", Array("NAME:CellLayerMerger", _
  "DrawLayers:=", Array("Measures:Measures", "Rats:Rats", "Errors:Errors", "Symbols:Symbols"))), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", -0.04064, "Degrees:=", 90, "Flip:=", false))
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:PassedParameterTab", Array("NAME:PropServers",  _
  oCompId), Array("NAME:ChangedProps", Array("NAME:R", "Value:=", "100ohms"))))
oCompId1 = oCompId & ":1"
oCompId2 = oCompId & ":2"
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:RotateParameters", "Degrees:=", 90, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Rotate Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:RotateParameters", "Degrees:=", 90, "Disconnect:=", false, "Rubberband:=", false)
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId2)), Array("NAME:MoveParameters", "xdelta:=", 0.00508, "ydelta:=", -0.00254, "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1940), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", -0.03556, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.04064, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oCompId = oEditor.CreatePagePort ( Array("NAME:PagePortProps", "Name:=", "DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2", "Id:=", 1950), _
  Array("NAME:Attributes", "Page:=", 1, "X:=", 0.1524, "Y:=", -0.04572, "Degrees:=", 0, "Flip:=", false))
oCompId1 = oCompId & ":1"
oEditor.Move Array("NAME:Selections", "Selections:=", Array( _
  oCompId1)), Array("NAME:MoveParameters", "xdelta:=", -0.04064, "ydelta:=", 0, _
  "Disconnect:=", false, "Rubberband:=", false)
oDesign.EditDesignOptions Array("NAME:NexximOptions", "LocalParamScope:=", true, "ForceResimulate:=",  _
false, "NumberOfProcessors:=", 6, "GlobalSettingForProcessors:=", false)

'TRANSIENT SIMULATION SETUP
Set oModule = oDesign.GetModule("SimSetup")
oModule.AddTransient Array("NAME:SimSetup", "DataBlockID:=", 10, "SimSetupID:=",  _
  1960, "OptionName:=", "(Default Options)", "AdditionalOptions:=", "", "AlterBlockName:=",  _
  "", "FilterText:=", "", "AnalysisEnabled:=", 1, Array("NAME:OutputQuantities"), Array("NAME:NoiseOutputQuantities"), "Name:=",  _
  "Transient1", "TransientData:=", Array("1E-10", "5E-09"), "TransientNoiseData:=", Array( _
 false, "", "", 0, 1, 0, false, 1))
oProject.Save

'CREATE A REPORT FOR PROBE/TERMINATION VOLTAGE WAVEFORMS
Set oModule = oDesign.GetModule("ReportSetup")
oModule.CreateReport "Voltage Waveform at Probe/Termination Nodes", "Standard", "Rectangular Plot", "Transient1", Array("NAME:Context", "SimValueContext:=", Array( _
  1, 0, 2, 0, false, false, -1, 1, 0, 1, 1, "", 0, 0, "DE", false, "0", "DP",  _
  false, "20000000", "DT", false, "0.001", "WE", false, "5E-09", "WM", false,  _
  "5E-09", "WN", false, "0", "WS", false, "0s")), Array("Time:=", Array("All")), Array("X Component:=",  _
  "Time", "Y Component:=", _
  Array( _
  "V(DRAM_D0_AD2_PBGA624_U1)", _
  "V(DRAM_D1_AE2_PBGA624_U1)", _
  "V(DRAM_D2_AC4_PBGA624_U1)", _
  "V(DRAM_D3_AA5_PBGA624_U1)", _
  "V(DRAM_D4_AC1_PBGA624_U1)", _
  "V(DRAM_D5_AD1_PBGA624_U1)", _
  "V(DRAM_D6_AB4_PBGA624_U1)", _
  "V(DRAM_D7_AE4_PBGA624_U1)", _
  "V(DRAM_DQS0_P_AE3_PBGA624_U1)", _
  "V(DRAM_DQS0_N_AD3_PBGA624_U1)"  _
  , _
  "V(DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)"  _
  )), Array()

'CREATE A REPORT FOR TDR PROBE WAVEFORMS
Set oModule = oDesign.GetModule("ReportSetup")
oModule.CreateReport "Waveforms at TDR Probes", "Standard", "Rectangular Plot", "Transient1", Array("NAME:Context", "SimValueContext:=", Array( _
  1, 0, 2, 0, false, false, -1, 1, 0, 1, 1, "", 0, 0, "DE", false, "0", "DP",  _
  false, "20000000", "DT", false, "0.001", "WE", false, "5E-09", "WM", false,  _
  "5E-09", "WN", false, "0", "WS", false, "0s")), Array("Time:=", Array("All")), Array("X Component:=",  _
  "Time", "Y Component:=", _
  Array( _
  "O(ADRAM_D0_AD2_PBGA624_U1:zl)", _
  "O(ADRAM_D1_AE2_PBGA624_U1:zl)", _
  "O(ADRAM_D2_AC4_PBGA624_U1:zl)", _
  "O(ADRAM_D3_AA5_PBGA624_U1:zl)", _
  "O(ADRAM_D4_AC1_PBGA624_U1:zl)", _
  "O(ADRAM_D5_AD1_PBGA624_U1:zl)", _
  "O(ADRAM_D6_AB4_PBGA624_U1:zl)", _
  "O(ADRAM_D7_AE4_PBGA624_U1:zl)", _
  "O(ADRAM_DQS0_P_AE3_PBGA624_U1:zdiff)"  _
  )), Array()


'UNSELECT ALL  AND  FIT SCHEMATIC
oEditor.SetSIWizardMode(false)
oEditor.SelectElement Array("NAME:Selections", "Selections:=", Array(""))
oEditor.ZoomToFit


'EXECUTE TRANSIENT SIMULATION
oDesign.Analyze "Transient1"
oProject.Save
SetLocale(locale)
oDesktop.EnableAutoSave(autoSave)
