' ----------------------------------------------
' Script generated by SIwave - TDR Wizard with Netlist
' Sun Nov 26 09:47:55 2023
' ----------------------------------------------
Dim oAnsoftApp
Dim oDesktop
Dim oProject
Dim oDesign
Dim oModule
Set oAnsoftApp = CreateObject("Ansoft.ElectronicsDesktop.2022.2")
Set oDesktop = oAnsoftApp.GetAppDesktop()
oDesktop.RestoreWindow

Set oProject = oDesktop.OpenProject("C:/Users/SGI-U3/Documents/GitHub/Ansys/siwave/_03_openrex_u14_disjoint/openrex_edb_v3.siwaveresults/DesignerTDR/TDR1.aedt")
Set oDesign = oProject.SetActiveDesign("openrex_edb_v3_TDR1")
oDesign.Analyze

'CREATE A REPORT FOR PROBE/TERMINATION VOLTAGE WAVEFORMS
Set oModule = oDesign.GetModule("ReportSetup")
oModule.CreateReport "Voltage Waveform at Probe/Termination Nodes", "Standard", "Rectangular Plot", "TRAN", Array("NAME:Context", "SimValueContext:=", Array( _
  1, 0, 2, 0, false, false, -1, 1, 0, 1, 1, "", 0, 0, "DE", false, "0", "DP",  _
  false, "20000000", "DT", false, "0.001", "WE", false, "5E-09", "WM", false,  _
  "5E-09", "WN", false, "0", "WS", false, "0s")), Array("Time:=", Array("All")), Array("X Component:=",  _
  "Time", "Y Component:=", _
  Array( _
  "V(DRAM_D0_AD2_PBGA624_U1)", _
  "V(DRAM_D1_AE2_PBGA624_U1)", _
  "V(DRAM_D2_AC4_PBGA624_U1)", _
  "V(DRAM_D3_AA5_PBGA624_U1)", _
  "V(DRAM_D4_AC1_PBGA624_U1)", _
  "V(DRAM_D5_AD1_PBGA624_U1)", _
  "V(DRAM_D6_AB4_PBGA624_U1)", _
  "V(DRAM_D7_AE4_PBGA624_U1)", _
  "V(DRAM_DQS0_P_AE3_PBGA624_U1)", _
  "V(DRAM_DQS0_N_AD3_PBGA624_U1)"  _
  , _
  "V(DRAM_D0_E3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D1_H3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D2_H7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D3_F8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D4_F2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D5_G2_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D6_F7_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_D7_H8_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_DQS0_P_F3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)", _
  "V(DRAM_DQS0_N_G3_96_FPGA_DD3_14MMX10MM-SMALL_SIZE_U2)"  _
  )), Array()

'CREATE A REPORT FOR TDR PROBE WAVEFORMS
Set oModule = oDesign.GetModule("ReportSetup")
oModule.CreateReport "Waveforms at TDR Probes", "Standard", "Rectangular Plot", "TRAN", Array("NAME:Context", "SimValueContext:=", Array( _
  1, 0, 2, 0, false, false, -1, 1, 0, 1, 1, "", 0, 0, "DE", false, "0", "DP",  _
  false, "20000000", "DT", false, "0.001", "WE", false, "5E-09", "WM", false,  _
  "5E-09", "WN", false, "0", "WS", false, "0s")), Array("Time:=", Array("All")), Array("X Component:=",  _
  "Time", "Y Component:=", _
  Array( _
  "O(ADRAM_D0_AD2_PBGA624_U1:zl)", _
  "O(ADRAM_D1_AE2_PBGA624_U1:zl)", _
  "O(ADRAM_D2_AC4_PBGA624_U1:zl)", _
  "O(ADRAM_D3_AA5_PBGA624_U1:zl)", _
  "O(ADRAM_D4_AC1_PBGA624_U1:zl)", _
  "O(ADRAM_D5_AD1_PBGA624_U1:zl)", _
  "O(ADRAM_D6_AB4_PBGA624_U1:zl)", _
  "O(ADRAM_D7_AE4_PBGA624_U1:zl)", _
  "O(ADRAM_DQS0_P_AE3_PBGA624_U1:zdiff)"  _
  )), Array()
oProject.Save
